version: 2
jobs:
  build:
    machine: true
    steps:
#      - add_ssh_keys:
 #         fingerprints:
  #          - "ff:4f:70:f0:90:f3:48:62:bc:b5:d8:db:a0:50:89:c2"
      - run:
          name: Deploy Over SSH
          command: |
            ssh -vvv ubuntu@52.66.65.62 "cd ci/ap/ &&  sudo git pull https://9efdf5cfaa61d7a979f87bd9724b47778c9cb73d:x-oauth-basic@github.com/rounakmakwane/test.git && sudo chown -R ubuntu:www-data ci/ap/"
      - run:
          name: Deploy Over SSH
          command: |
            ssh -vvv ubuntu@13.232.242.124 "cd ci/ap/ &&  sudo git pull https://9efdf5cfaa61d7a979f87bd9724b47778c9cb73d:x-oauth-basic@github.com/rounakmakwane/test.git && sudo chown -R ubuntu:www-data ci/ap/"
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
