version: 2
jobs:
  build:
    machine: true
    steps:
      - run:
          name: Deploy Over SSH
          command: |
            ssh ubuntu@13.126.205.29 "mkdir test"
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
