version: 2
jobs:
  build:
    docker:
      - image: circleci/node:4.8.2-jessie
    steps:
      - run:
          name: Deploy Over SSH
          command: |
            ssh 13.126.205.29@$ubuntu "mkdir test"
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
